"""baseline

Revision ID: 6707ad441599
Revises:
Create Date: 2026-07-16 16:57:42.127356

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6707ad441599"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "code_repositories",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("GITHUB", "GITLAB", "BITBUCKET", name="repository_provider"),
            nullable=False,
        ),
        sa.Column("owner", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("clone_url", sa.String(), nullable=False),
        sa.Column("default_branch", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_code_repositories")),
        sa.UniqueConstraint(
            "provider", "owner", "name", name=op.f("uq_code_repositories_provider_owner_name")
        ),
    )
    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", "CANCELLED", name="scan_run_status"
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("commit_sha", sa.String(), nullable=False),
        sa.Column("ref", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["code_repositories.id"],
            name=op.f("fk_scan_runs_repository_id_code_repositories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_runs")),
    )
    op.create_index(
        op.f("ix_scan_runs_repository_id"), "scan_runs", ["repository_id"], unique=False
    )
    op.create_index(op.f("ix_scan_runs_status"), "scan_runs", ["status"], unique=False)
    op.create_table(
        "scan_tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scan_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "scanner_type",
            sa.Enum("SAST", "DAST", "SCA", "SECRETS", "IAC", name="scanner_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "RUNNING", "COMPLETED", "FAILED", "SKIPPED", name="scan_task_status"
            ),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_run_id"],
            ["scan_runs.id"],
            name=op.f("fk_scan_tasks_scan_run_id_scan_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_tasks")),
        sa.UniqueConstraint(
            "scan_run_id", "scanner_type", name=op.f("uq_scan_tasks_scan_run_id_scanner_type")
        ),
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scan_task_id", sa.Uuid(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO", name="finding_severity"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("OPEN", "RESOLVED", "SUPPRESSED", "FALSE_POSITIVE", name="finding_status"),
            server_default="OPEN",
            nullable=False,
        ),
        sa.Column("rule_id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("fingerprint", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=True),
        sa.Column("line_number", sa.Integer(), nullable=True),
        sa.Column(
            "raw_evidence",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scan_task_id"],
            ["scan_tasks.id"],
            name=op.f("fk_findings_scan_task_id_scan_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint(
            "scan_task_id", "fingerprint", name=op.f("uq_findings_scan_task_id_fingerprint")
        ),
    )
    op.create_index(op.f("ix_findings_severity"), "findings", ["severity"], unique=False)
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_severity"), table_name="findings")
    op.drop_table("findings")
    op.drop_table("scan_tasks")
    op.drop_index(op.f("ix_scan_runs_status"), table_name="scan_runs")
    op.drop_index(op.f("ix_scan_runs_repository_id"), table_name="scan_runs")
    op.drop_table("scan_runs")
    op.drop_table("code_repositories")
    # ### end Alembic commands ###
    # Manually added: `op.create_table(..., sa.Column(..., sa.Enum(...)))` implicitly
    # issues `CREATE TYPE` for each native Postgres enum, but Alembic's autogenerate
    # does not add the matching `DROP TYPE` to `downgrade()` — without these, a
    # subsequent `upgrade head` fails with "type already exists".
    bind = op.get_bind()
    sa.Enum(name="repository_provider").drop(bind, checkfirst=True)
    sa.Enum(name="scan_run_status").drop(bind, checkfirst=True)
    sa.Enum(name="scan_task_status").drop(bind, checkfirst=True)
    sa.Enum(name="scanner_type").drop(bind, checkfirst=True)
    sa.Enum(name="finding_severity").drop(bind, checkfirst=True)
    sa.Enum(name="finding_status").drop(bind, checkfirst=True)
